name: Build Spring Boot App


on:
  push:
    branches:
      - main


jobs:
  build_executable_jar:
    runs-on: [self-hosted, quickbite] # Sử dụng Self-hosted runner của tổ chức
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v5

      - name: Cài đặt môi trường JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cấp quyền thực thi cho Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Biên dịch và đóng gói tệp JAR (Bỏ qua tác vụ Test)
        run: ./gradlew bootJar

      - name: Lưu trữ sản phẩm (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: user-service-jar
          path: build/libs/*.jar
          retention-days: 3

